title: Creating my first website
author: spud
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The goal is to create my first website using github. I believe this software and community will help me accomplish my goals.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
